---
title: "_week2."
author: "Hamere Mogus"
date: "2024-02-07"
output: html_document
---
install.packages("dplyr")
library("dplyr")
install.packages("ggplot2")
library("ggplot2")
#
?Indometh
data("Indometh")
#data structure- The Indometh dataset has 66 observations across 3 variables. The variables are:
#Subject(a factor variable ranging from 1-6)
#Time(a numeric vector indicating the time of observation per hour at which blood samples were drawn)
#Concentration(a numeric vector representing the concentration of Indometacin in mcg/ml)
str(Indometh)
nrow(Indometh)
ncol(Indometh)
head(Indometh)
tail(Indometh)
View(Indometh)
#table- gives us the frequency counts of each variable 
#prop.table- gives us the relative frequency of each variable 
#both will help us understand the distribution of observations across different variables/experimental conditions.
table(Indometh$Subject)
prop.table(table(Indometh$Subject))
table(Indometh$time)
prop.table(table(Indometh$time))
table(Indometh$conc)
prop.table(table(Indometh$conc))
#summary statistics for each variable- helpful to understand the distribution and central tendency of each variable
summary(Indometh)
summary(Indometh$subject)
summary(Indometh$time)
fivenum(Indometh$time)
summary(Indometh$conc)
fivenum(Indometh$conc)
# data visualization- for numeric variables
hist(Indometh$time, main="Histogram of Time", xlab="Time", col="lightgreen")
hist(Indometh$conc, main="Histogram of Concentration", xlab="Concentration", col="lightblue")

#Short Description:
#The summary for dataset Indometh indicates that there are 11 observations for Subjects 1-6 represting a normal distribution across the subjects. The minimum and maximum time recorded for the time variable are 0.250 and 8.000 respectively. The 25th percentile of time measurement is at 0.750, the 50th percentile is at 5.000, the 75th percentile is at 5.000 and the mean is approximately 2.886. The minimum and maximum concentration recorded for the conc variable are 0.0500 and 2.7200 respectively. The 25th percentile of concentration measurement is at 0.1100, the 50th percentile is at 0.3400, the 75th percentile is at 0.8325 and the mean is approximately 0.5918. As time variable increased, concentration seemed to decrease indicating a negative correlation. 
